feat: add types
libp2p/js-libp2p-utils pull request #16
Opened 2021-03-26 15:01 UTC by vasco-santos

2021-04-06 13:05 UTC, hugomrdias requested changes

2021-04-06 13:05 UTC, hugomrdias commented on src/stream-to-ma-conn.js
> +        // @ts-ignore abortable has no type definitions
it should have https://github.com/alanshaw/abortable-iterator/blob/master/index.d.ts

2021-04-06 13:05 UTC, hugomrdias commented on tsconfig.json
> +  "extends": "./node_modules/aegir/src/config/tsconfig.aegir.json",
```suggestion
  "extends": "aegir/src/config/tsconfig.aegir.json",
```

2021-04-06 13:05 UTC, hugomrdias commented on src/ip-port-to-multiaddr.js
> +  // @ts-ignore parseInt expects only string
better to just wrap with an if clause

2021-04-06 14:03 UTC, vasco-santos commented on src/stream-to-ma-conn.js
> +        // @ts-ignore abortable has no type definitions
I retried it deconstructing the require and it has types indeed. However, types infer that the Uint8Array will be a source with numbers for reasons 🤷🏼 I updated the ignore message to not block on this

2021-04-06 17:29 UTC, achingbrain commented on src/ip-port-to-multiaddr.js
> +  } catch (_) {}
If you're ignoring the error you can use optional catch binding here:

```suggestion
  } catch {}
```

2021-04-06 17:30 UTC, achingbrain commented on src/ip-port-to-multiaddr.js
> +  } catch (err) {
Should this error get logged somewhere?

2021-04-06 17:32 UTC, achingbrain commented on src/stream-to-ma-conn.js
> +    // @ts-ignore abortable has no type definitions
An `index.d.ts` was added two years ago? https://github.com/alanshaw/abortable-iterator/commit/c3c68a1888a114de64f9e350cf8f725514b08c41#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8

2021-04-06 19:58 UTC, vasco-santos commented on src/stream-to-ma-conn.js
> +    // @ts-ignore abortable has no type definitions
I understand why, I will open an issue in `abortable-iterator`. It is not exporting correctly the types in the default for some reason. I get `abortable is not callable`
However, if we do `const { source: abortable } = require('abortable-iterator')` it will infer the types correctly

2021-04-07 09:41 UTC, rvagg approved these changes
seems fine to me

2021-04-08 09:52 UTC, merged